name: Auto release on version change

on:
  push:
    branches: [ main, master ]
    paths:
      - 'serialized-search-replace.php'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  call-reusable:
    uses: mathrim87/.github/.github/workflows/wp-plugin-auto-release.yml@main
    with:
      plugin_main_file: serialized-search-replace.php
      plugin_slug: serialized-search-replace
    secrets: inherit


